name: Python CI

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff pre-commit

    - name: Run Ruff
      run: |
        ruff check . --fix  # Automatically fix issues if needed

    - name: Run pre-commit hooks
      run: pre-commit run --all-files  # Manually run the pre-commit hooks
