name: Build and Release Docker Image

on:
  push:
    tags:
      - 'v*'  # Trigger the action on version tags (e.g., v1.0, v1.1)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Set up Docker Compose
    - name: Set up Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version  # Verify the installation

    # Build Docker Compose services
    - name: Build Docker Compose services
      run: |
        docker-compose -f docker-compose.yml build

    # Tag the image with the version tag instead of SHA
    - name: Tag Docker image
      run: |
        docker tag reverse_proxy:latest reverse_proxy:${{ github.ref_name }}

    # Save the Docker image as a tar file
    - name: Save Docker image as a tar file
      run: |
        docker save reverse_proxy:${{ github.ref_name }} | gzip > reverse_proxy-${{ github.ref_name }}.tar.gz

    # Upload the tar file as an asset to GitHub Release
    - name: Upload Docker image as release asset
      uses: softprops/action-gh-release@v1
      with:
        files: reverse_proxy-${{ github.ref_name }}.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
